# Generated by Django 4.0.5 on 2022-07-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('orderId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'orderlist',
            },
        ),
    ]
